version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: app
    docker: 
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t app .
workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: master